- name: Create Google credentials file
        env:
          GOOGLE_CREDS: ${{ secrets.GOOGLE_ADC_CREDENTIALS }}
        run: python3 -c "import os; open('/tmp/gcloud_adc.json','w').write(os.environ['GOOGLE_CREDS'])"
